//! READ command pack/unpack skeleton migrated from `lib/smb2-cmd-read.c`.

/// SMB2 header length used when translating payload offsets.
pub const SMB2_HEADER_SIZE: usize = 64;

/// Legacy `SMB2_FD_SIZE`, the fixed-size file identifier in READ requests.
pub const SMB2_FD_SIZE: usize = 16;

/// Wire `StructureSize` value for READ requests.
pub const SMB2_READ_REQUEST_SIZE: u16 = 49;

/// Wire `StructureSize` value for READ replies.
pub const SMB2_READ_REPLY_SIZE: u16 = 17;

const READ_REQUEST_FIXED_LEN: usize = (SMB2_READ_REQUEST_SIZE as usize) & !1;
const READ_REPLY_FIXED_LEN: usize = (SMB2_READ_REPLY_SIZE as usize) & !1;
const READ_REPLY_DATA_OFFSET: u8 = (SMB2_HEADER_SIZE + READ_REPLY_FIXED_LEN) as u8;

/// Error type for READ command skeleton packing and parsing.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ReadCommandError {
    /// A fixed payload is shorter than the SMB2 READ structure requires.
    ShortFixedPayload { expected: usize, actual: usize },
    /// The fixed payload advertises an unexpected SMB2 structure size.
    UnexpectedStructureSize { expected: u16, actual: u16 },
    /// A READ reply contains data at an offset other than the C implementation expects.
    UnexpectedDataOffset { expected: u8, actual: u8 },
    /// READ channel information overlaps the fixed request body.
    ChannelInfoOverlapsRequest,
    /// The requested read length exceeds the caller-supplied maximum.
    ReadLengthExceedsMaximum { requested: u32, maximum: u32 },
    /// A reply buffer was required by the C async path but was not supplied.
    MissingReplyBuffer,
}

/// Convenient result alias for READ command skeleton operations.
pub type ReadCommandResult<T> = Result<T, ReadCommandError>;

/// Minimal iovec-style byte segment used by the READ command skeleton.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Smb2IoVector {
    data: Vec<u8>,
}

impl Smb2IoVector {
    /// Creates a new byte vector segment.
    pub fn new(data: Vec<u8>) -> Self {
        Self { data }
    }

    /// Returns the segment bytes.
    pub fn as_slice(&self) -> &[u8] {
        &self.data
    }

    /// Returns the segment length.
    pub fn len(&self) -> usize {
        self.data.len()
    }

    /// Returns true when the segment is empty.
    pub fn is_empty(&self) -> bool {
        self.data.is_empty()
    }
}

/// Minimal PDU shape for READ command encode/decode skeletons.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Smb2ReadPdu {
    /// Outgoing vectors generated by request/reply encoders.
    pub out: Vec<Smb2IoVector>,
    /// Incoming vectors expected or consumed by request/reply processors.
    pub input: Vec<Smb2IoVector>,
    /// Credit charge calculated for multi-credit READ requests.
    pub credit_charge: u16,
}

impl Smb2ReadPdu {
    /// Creates an empty READ PDU skeleton.
    pub fn new() -> Self {
        Self::default()
    }

    /// Adds an outgoing byte segment.
    pub fn push_out(&mut self, data: Vec<u8>) {
        self.out.push(Smb2IoVector::new(data));
    }

    /// Adds an incoming byte segment.
    pub fn push_input(&mut self, data: Vec<u8>) {
        self.input.push(Smb2IoVector::new(data));
    }
}

/// Rust counterpart of `struct smb2_read_request`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Smb2ReadRequest {
    /// READ request flags.
    pub flags: u8,
    /// Requested byte count.
    pub length: u32,
    /// File offset to read from.
    pub offset: u64,
    /// SMB2 file identifier.
    pub file_id: [u8; SMB2_FD_SIZE],
    /// Minimum byte count accepted by the caller.
    pub minimum_count: u32,
    /// Channel selector.
    pub channel: u32,
    /// Remaining bytes advertised by the caller.
    pub remaining_bytes: u32,
    /// Absolute SMB2 packet offset of channel info.
    pub read_channel_info_offset: u16,
    /// Length of optional channel info.
    pub read_channel_info_length: u16,
    /// Optional READ channel info bytes.
    pub read_channel_info: Vec<u8>,
    /// Optional application-provided reply buffer length marker.
    pub reply_buffer_len: Option<u32>,
}

impl Default for Smb2ReadRequest {
    fn default() -> Self {
        Self {
            flags: 0,
            length: 0,
            offset: 0,
            file_id: [0; SMB2_FD_SIZE],
            minimum_count: 0,
            channel: 0,
            remaining_bytes: 0,
            read_channel_info_offset: 0,
            read_channel_info_length: 0,
            read_channel_info: Vec::new(),
            reply_buffer_len: None,
        }
    }
}

impl Smb2ReadRequest {
    /// Encodes the fixed READ request fields and optional raw channel info.
    pub fn encode_request(
        &mut self,
        supports_multi_credit: bool,
        _passthrough: bool,
    ) -> ReadCommandResult<Vec<Smb2IoVector>> {
        if !supports_multi_credit && self.length > 64 * 1024 {
            self.length = 64 * 1024;
            self.minimum_count = 0;
        }

        let mut fixed = vec![0; READ_REQUEST_FIXED_LEN];
        put_u16(&mut fixed, 0, SMB2_READ_REQUEST_SIZE);
        put_u8(&mut fixed, 3, self.flags);
        put_u32(&mut fixed, 4, self.length);
        put_u64(&mut fixed, 8, self.offset);
        fixed[16..32].copy_from_slice(&self.file_id);
        put_u32(&mut fixed, 32, self.minimum_count);
        put_u32(&mut fixed, 36, self.channel);
        put_u32(&mut fixed, 40, self.remaining_bytes);
        put_u16(&mut fixed, 46, self.read_channel_info_length);

        let mut vectors = vec![Smb2IoVector::new(fixed)];
        if self.read_channel_info_length > 0 && !self.read_channel_info.is_empty() {
            self.read_channel_info_offset = (READ_REQUEST_FIXED_LEN + SMB2_HEADER_SIZE) as u16;
            put_u16(&mut vectors[0].data, 44, self.read_channel_info_offset);

            let info_len = usize::from(self.read_channel_info_length);
            let copy_len = info_len.min(self.read_channel_info.len());
            let padded_len = pad_to_64bit(info_len);
            let mut channel_info = vec![0; padded_len];
            channel_info[..copy_len].copy_from_slice(&self.read_channel_info[..copy_len]);
            vectors.push(Smb2IoVector::new(channel_info));
        }

        if self.read_channel_info_length == 0 {
            vectors.push(Smb2IoVector::new(vec![0]));
        }

        Ok(vectors)
    }

    /// Validates the async READ request skeleton and calculates credit charge.
    ///
    /// # Errors
    ///
    /// Returns an error when a non-empty READ has no reply buffer marker.
    pub fn cmd_read_async(
        &mut self,
        supports_multi_credit: bool,
        passthrough: bool,
    ) -> ReadCommandResult<Smb2ReadPdu> {
        if self.length > 0 && self.reply_buffer_len.is_none() {
            return Err(ReadCommandError::MissingReplyBuffer);
        }

        let mut pdu = Smb2ReadPdu::new();
        pdu.out = self.encode_request(supports_multi_credit, passthrough)?;
        if let Some(reply_len) = self.reply_buffer_len {
            if reply_len > 0 {
                pdu.push_input(vec![0; reply_len as usize]);
            }
        }
        pdu.credit_charge = credit_charge(self.length, supports_multi_credit);
        Ok(pdu)
    }

    /// Parses the fixed READ request payload and returns the variable byte count to read next.
    ///
    /// # Errors
    ///
    /// Returns an error when the fixed payload is too short, advertises an
    /// unexpected structure size, exceeds the configured read limit, or points
    /// channel info into the fixed request body.
    pub fn process_request_fixed(
        fixed: &[u8],
        max_read_size: u32,
    ) -> ReadCommandResult<(Self, usize)> {
        require_len(fixed, READ_REQUEST_FIXED_LEN)?;
        let structure_size = get_u16(fixed, 0);
        if structure_size != SMB2_READ_REQUEST_SIZE || fixed.len() != READ_REQUEST_FIXED_LEN {
            return Err(ReadCommandError::UnexpectedStructureSize {
                expected: SMB2_READ_REQUEST_SIZE,
                actual: structure_size,
            });
        }

        let mut file_id = [0; SMB2_FD_SIZE];
        file_id.copy_from_slice(&fixed[16..32]);

        let length = get_u32(fixed, 4);
        if length > max_read_size {
            return Err(ReadCommandError::ReadLengthExceedsMaximum {
                requested: length,
                maximum: max_read_size,
            });
        }

        let read_channel_info_offset = get_u16(fixed, 44);
        let read_channel_info_length = get_u16(fixed, 46);
        if read_channel_info_length == 0 {
            return Ok((
                Self {
                    flags: get_u8(fixed, 3),
                    length,
                    offset: get_u64(fixed, 8),
                    file_id,
                    minimum_count: get_u32(fixed, 32),
                    channel: get_u32(fixed, 36),
                    remaining_bytes: get_u32(fixed, 40),
                    read_channel_info_offset,
                    read_channel_info_length,
                    read_channel_info: Vec::new(),
                    reply_buffer_len: None,
                },
                0,
            ));
        }

        let minimum_offset = SMB2_HEADER_SIZE + READ_REQUEST_FIXED_LEN;
        if usize::from(read_channel_info_offset) < minimum_offset {
            return Err(ReadCommandError::ChannelInfoOverlapsRequest);
        }

        let variable_len = usize::from(read_channel_info_offset)
            .checked_sub(minimum_offset)
            .and_then(|offset| offset.checked_add(usize::from(read_channel_info_length)))
            .ok_or(ReadCommandError::ChannelInfoOverlapsRequest)?;
        Ok((
            Self {
                flags: get_u8(fixed, 3),
                length,
                offset: get_u64(fixed, 8),
                file_id,
                minimum_count: get_u32(fixed, 32),
                channel: get_u32(fixed, 36),
                remaining_bytes: get_u32(fixed, 40),
                read_channel_info_offset,
                read_channel_info_length,
                read_channel_info: Vec::new(),
                reply_buffer_len: None,
            },
            variable_len,
        ))
    }

    /// Attaches variable READ channel info bytes parsed after the fixed request body.
    ///
    /// # Errors
    ///
    /// Returns an error when `variable` is shorter than the declared channel-info length.
    pub fn process_request_variable(&mut self, variable: &[u8]) -> ReadCommandResult<()> {
        let needed = usize::from(self.read_channel_info_length);
        if needed == 0 {
            self.read_channel_info.clear();
            return Ok(());
        }

        let minimum_offset = SMB2_HEADER_SIZE + READ_REQUEST_FIXED_LEN;
        let channel_offset = usize::from(self.read_channel_info_offset)
            .checked_sub(minimum_offset)
            .ok_or(ReadCommandError::ChannelInfoOverlapsRequest)?;
        let required_len = channel_offset + needed;
        if variable.len() < required_len {
            return Err(ReadCommandError::ShortFixedPayload {
                expected: required_len,
                actual: variable.len(),
            });
        }
        self.read_channel_info.clear();
        self.read_channel_info
            .extend_from_slice(&variable[channel_offset..required_len]);
        Ok(())
    }
}

/// Rust counterpart of `struct smb2_read_reply`.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Smb2ReadReply {
    /// Absolute SMB2 packet offset of reply data.
    pub data_offset: u8,
    /// Length of reply data.
    pub data_length: u32,
    /// Bytes remaining after this reply.
    pub data_remaining: u32,
    /// Reply data bytes or a borrowed-copy placeholder from the variable vector.
    pub data: Vec<u8>,
}

impl Smb2ReadReply {
    /// Encodes the fixed READ reply fields and optional data vector.
    pub fn encode_reply(&mut self) -> Vec<Smb2IoVector> {
        let mut fixed = vec![0; READ_REPLY_FIXED_LEN];
        self.data_offset = 0;
        if self.data_length > 0 && !self.data.is_empty() {
            self.data_offset = READ_REPLY_DATA_OFFSET;
        }

        put_u16(&mut fixed, 0, SMB2_READ_REPLY_SIZE);
        put_u8(&mut fixed, 2, self.data_offset);
        put_u32(&mut fixed, 4, self.data_length);
        put_u32(&mut fixed, 8, self.data_remaining);

        let mut vectors = vec![Smb2IoVector::new(fixed)];
        if self.data_length > 0 && !self.data.is_empty() {
            vectors.push(Smb2IoVector::new(self.data.clone()));
        }
        vectors
    }

    /// Creates an outgoing READ reply PDU skeleton.
    pub fn cmd_read_reply_async(&mut self) -> Smb2ReadPdu {
        let mut pdu = Smb2ReadPdu::new();
        pdu.out = self.encode_reply();
        pdu
    }

    /// Parses the fixed READ reply payload and returns the variable byte count to read next.
    ///
    /// # Errors
    ///
    /// Returns an error when the fixed payload is too short, advertises an
    /// unexpected structure size, or uses an unexpected data offset.
    pub fn process_reply_fixed(fixed: &[u8]) -> ReadCommandResult<(Self, usize)> {
        require_len(fixed, READ_REPLY_FIXED_LEN)?;
        let structure_size = get_u16(fixed, 0);
        if structure_size != SMB2_READ_REPLY_SIZE || fixed.len() != READ_REPLY_FIXED_LEN {
            return Err(ReadCommandError::UnexpectedStructureSize {
                expected: SMB2_READ_REPLY_SIZE,
                actual: structure_size,
            });
        }

        let data_offset = get_u8(fixed, 2);
        let data_length = get_u32(fixed, 4);
        if data_length == 0 {
            return Ok((
                Self {
                    data_offset,
                    data_length,
                    data_remaining: get_u32(fixed, 8),
                    data: Vec::new(),
                },
                0,
            ));
        }

        if data_offset != READ_REPLY_DATA_OFFSET {
            return Err(ReadCommandError::UnexpectedDataOffset {
                expected: READ_REPLY_DATA_OFFSET,
                actual: data_offset,
            });
        }

        Ok((
            Self {
                data_offset,
                data_length,
                data_remaining: get_u32(fixed, 8),
                data: Vec::new(),
            },
            data_length as usize,
        ))
    }

    /// Attaches variable READ reply data bytes parsed after the fixed reply body.
    ///
    /// # Errors
    ///
    /// Returns an error when `variable` is shorter than the declared data length.
    pub fn process_reply_variable(&mut self, variable: &[u8]) -> ReadCommandResult<()> {
        let needed =
            usize::try_from(self.data_length).map_err(|_| ReadCommandError::ShortFixedPayload {
                expected: usize::MAX,
                actual: variable.len(),
            })?;
        if variable.len() < needed {
            return Err(ReadCommandError::ShortFixedPayload {
                expected: needed,
                actual: variable.len(),
            });
        }
        self.data.clear();
        self.data.extend_from_slice(&variable[..needed]);
        Ok(())
    }
}

fn credit_charge(length: u32, supports_multi_credit: bool) -> u16 {
    if supports_multi_credit && length > 0 {
        ((length - 1) / 65_536 + 1) as u16
    } else {
        0
    }
}

fn pad_to_64bit(length: usize) -> usize {
    (length + 7) & !7
}

fn require_len(buf: &[u8], expected: usize) -> ReadCommandResult<()> {
    if buf.len() < expected {
        Err(ReadCommandError::ShortFixedPayload {
            expected,
            actual: buf.len(),
        })
    } else {
        Ok(())
    }
}

fn get_u8(buf: &[u8], offset: usize) -> u8 {
    buf[offset]
}

fn get_u16(buf: &[u8], offset: usize) -> u16 {
    u16::from_le_bytes([buf[offset], buf[offset + 1]])
}

fn get_u32(buf: &[u8], offset: usize) -> u32 {
    u32::from_le_bytes([
        buf[offset],
        buf[offset + 1],
        buf[offset + 2],
        buf[offset + 3],
    ])
}

fn get_u64(buf: &[u8], offset: usize) -> u64 {
    u64::from_le_bytes([
        buf[offset],
        buf[offset + 1],
        buf[offset + 2],
        buf[offset + 3],
        buf[offset + 4],
        buf[offset + 5],
        buf[offset + 6],
        buf[offset + 7],
    ])
}

fn put_u8(buf: &mut [u8], offset: usize, value: u8) {
    buf[offset] = value;
}

fn put_u16(buf: &mut [u8], offset: usize, value: u16) {
    buf[offset..offset + 2].copy_from_slice(&value.to_le_bytes());
}

fn put_u32(buf: &mut [u8], offset: usize, value: u32) {
    buf[offset..offset + 4].copy_from_slice(&value.to_le_bytes());
}

fn put_u64(buf: &mut [u8], offset: usize, value: u64) {
    buf[offset..offset + 8].copy_from_slice(&value.to_le_bytes());
}
