#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PlatformConfig {
    pub configure_option_tcp_linger: Option<u32>,
    pub have_arpa_inet_h: Option<u32>,
    pub have_dlfcn_h: Option<u32>,
    pub have_errno_h: Option<u32>,
    pub have_fcntl_h: Option<u32>,
    pub have_gssapi_gssapi_h: Option<u32>,
    pub have_inttypes_h: Option<u32>,
    pub have_libkrb5: Option<u32>,
    pub have_libnsl: Option<u32>,
    pub have_libsocket: Option<u32>,
    pub have_linger: Option<u32>,
    pub have_netdb_h: Option<u32>,
    pub have_netinet_in_h: Option<u32>,
    pub have_netinet_tcp_h: Option<u32>,
    pub have_poll_h: Option<u32>,
    pub have_sockaddr_len: Option<u32>,
    pub have_sockaddr_storage: Option<u32>,
    pub have_stdint_h: Option<u32>,
    pub have_stdio_h: Option<u32>,
    pub have_stdlib_h: Option<u32>,
    pub have_strings_h: Option<u32>,
    pub have_string_h: Option<u32>,
    pub have_sys_errno_h: Option<u32>,
    pub have_sys_fcntl_h: Option<u32>,
    pub have_sys_ioctl_h: Option<u32>,
    pub have_sys_poll_h: Option<u32>,
    pub have_sys_socket_h: Option<u32>,
    pub have_sys_stat_h: Option<u32>,
    pub have_sys_time_h: Option<u32>,
    pub have_sys_types_h: Option<u32>,
    pub have_sys_uio_h: Option<u32>,
    pub have_sys_unistd_h: Option<u32>,
    pub have_sys_iovec_h: Option<u32>,
    pub have_time_h: Option<u32>,
    pub have_unistd_h: Option<u32>,
    pub lt_objdir: &'static str,
    pub package: &'static str,
    pub package_bugreport: &'static str,
    pub package_name: &'static str,
    pub package_string: &'static str,
    pub package_tarname: &'static str,
    pub package_url: &'static str,
    pub package_version: &'static str,
    pub stdc_headers: Option<u32>,
    pub version: &'static str,
}

pub const AMIGA_OS_CONFIG: PlatformConfig = PlatformConfig {
    configure_option_tcp_linger: Some(1),
    have_arpa_inet_h: Some(1),
    have_dlfcn_h: Some(1),
    have_errno_h: Some(1),
    have_fcntl_h: Some(1),
    have_gssapi_gssapi_h: None,
    have_inttypes_h: Some(1),
    have_libkrb5: None,
    have_libnsl: None,
    have_libsocket: None,
    have_linger: None,
    have_netdb_h: Some(1),
    have_netinet_in_h: Some(1),
    have_netinet_tcp_h: Some(1),
    have_poll_h: None,
    have_sockaddr_len: Some(1),
    have_sockaddr_storage: None,
    have_stdint_h: Some(1),
    have_stdio_h: Some(1),
    have_stdlib_h: Some(1),
    have_strings_h: Some(1),
    have_string_h: Some(1),
    have_sys_errno_h: Some(1),
    have_sys_fcntl_h: Some(1),
    have_sys_ioctl_h: Some(1),
    have_sys_poll_h: None,
    have_sys_socket_h: Some(1),
    have_sys_stat_h: Some(1),
    have_sys_time_h: Some(1),
    have_sys_types_h: Some(1),
    have_sys_uio_h: Some(1),
    have_sys_unistd_h: Some(1),
    have_sys_iovec_h: None,
    have_time_h: Some(1),
    have_unistd_h: Some(1),
    lt_objdir: ".libs/",
    package: "libsmb2",
    package_bugreport: "ronniesahlberg@gmail.com",
    package_name: "libsmb2",
    package_string: "libsmb2 4.0.0",
    package_tarname: "libsmb2",
    package_url: "",
    package_version: "4.0.0",
    stdc_headers: Some(1),
    version: "4.0.0",
};

pub const APPLE_CONFIG: PlatformConfig = PlatformConfig {
    configure_option_tcp_linger: Some(1),
    have_arpa_inet_h: Some(1),
    have_dlfcn_h: Some(1),
    have_errno_h: Some(1),
    have_fcntl_h: Some(1),
    have_gssapi_gssapi_h: Some(1),
    have_inttypes_h: Some(1),
    have_libkrb5: None,
    have_libnsl: None,
    have_libsocket: None,
    have_linger: Some(1),
    have_netdb_h: Some(1),
    have_netinet_in_h: Some(1),
    have_netinet_tcp_h: Some(1),
    have_poll_h: Some(1),
    have_sockaddr_len: Some(1),
    have_sockaddr_storage: Some(1),
    have_stdint_h: Some(1),
    have_stdio_h: Some(1),
    have_stdlib_h: Some(1),
    have_strings_h: Some(1),
    have_string_h: Some(1),
    have_sys_errno_h: Some(1),
    have_sys_fcntl_h: Some(1),
    have_sys_ioctl_h: Some(1),
    have_sys_poll_h: Some(1),
    have_sys_socket_h: Some(1),
    have_sys_stat_h: Some(1),
    have_sys_time_h: Some(1),
    have_sys_types_h: Some(1),
    have_sys_uio_h: Some(1),
    have_sys_unistd_h: Some(1),
    have_sys_iovec_h: None,
    have_time_h: Some(1),
    have_unistd_h: Some(1),
    lt_objdir: ".libs/",
    package: "libsmb2",
    package_bugreport: "ronniesahlberg@gmail.com",
    package_name: "libsmb2",
    package_string: "libsmb2 4.0.0",
    package_tarname: "libsmb2",
    package_url: "",
    package_version: "4.0.0",
    stdc_headers: Some(1),
    version: "4.0.0",
};

pub const ESP_CONFIG: PlatformConfig = PlatformConfig {
    configure_option_tcp_linger: Some(1),
    have_arpa_inet_h: Some(1),
    have_dlfcn_h: Some(1),
    have_errno_h: Some(1),
    have_fcntl_h: Some(1),
    have_gssapi_gssapi_h: None,
    have_inttypes_h: Some(1),
    have_libkrb5: None,
    have_libnsl: None,
    have_libsocket: None,
    have_linger: Some(1),
    have_netdb_h: Some(1),
    have_netinet_in_h: Some(1),
    have_netinet_tcp_h: None,
    have_poll_h: None,
    have_sockaddr_len: None,
    have_sockaddr_storage: Some(1),
    have_stdint_h: Some(1),
    have_stdio_h: Some(1),
    have_stdlib_h: Some(1),
    have_strings_h: Some(1),
    have_string_h: Some(1),
    have_sys_errno_h: None,
    have_sys_fcntl_h: None,
    have_sys_ioctl_h: Some(1),
    have_sys_poll_h: Some(1),
    have_sys_socket_h: Some(1),
    have_sys_stat_h: Some(1),
    have_sys_time_h: None,
    have_sys_types_h: Some(1),
    have_sys_uio_h: Some(1),
    have_sys_unistd_h: None,
    have_sys_iovec_h: None,
    have_time_h: Some(1),
    have_unistd_h: Some(1),
    lt_objdir: ".libs/",
    package: "libsmb2",
    package_bugreport: "ronniesahlberg@gmail.com",
    package_name: "libsmb2",
    package_string: "libsmb2 4.0.0",
    package_tarname: "libsmb2",
    package_url: "",
    package_version: "4.0.0",
    stdc_headers: Some(1),
    version: "4.0.0",
};

pub const PICOW_CONFIG: PlatformConfig = PlatformConfig {
    configure_option_tcp_linger: Some(1),
    have_arpa_inet_h: None,
    have_dlfcn_h: Some(1),
    have_errno_h: None,
    have_fcntl_h: Some(1),
    have_gssapi_gssapi_h: None,
    have_inttypes_h: None,
    have_libkrb5: None,
    have_libnsl: None,
    have_libsocket: None,
    have_linger: None,
    have_netdb_h: None,
    have_netinet_in_h: None,
    have_netinet_tcp_h: None,
    have_poll_h: None,
    have_sockaddr_len: None,
    have_sockaddr_storage: Some(1),
    have_stdint_h: Some(1),
    have_stdio_h: Some(1),
    have_stdlib_h: Some(1),
    have_strings_h: None,
    have_string_h: None,
    have_sys_errno_h: None,
    have_sys_fcntl_h: None,
    have_sys_ioctl_h: None,
    have_sys_poll_h: None,
    have_sys_socket_h: None,
    have_sys_stat_h: Some(1),
    have_sys_time_h: None,
    have_sys_types_h: Some(1),
    have_sys_uio_h: None,
    have_sys_unistd_h: None,
    have_sys_iovec_h: None,
    have_time_h: Some(1),
    have_unistd_h: Some(1),
    lt_objdir: ".libs/",
    package: "libsmb2",
    package_bugreport: "ronniesahlberg@gmail.com",
    package_name: "libsmb2",
    package_string: "libsmb2 4.0.0",
    package_tarname: "libsmb2",
    package_url: "",
    package_version: "4.0.0",
    stdc_headers: Some(1),
    version: "4.0.0",
};

pub const PS3_CONFIG: PlatformConfig = PlatformConfig {
    configure_option_tcp_linger: Some(1),
    have_arpa_inet_h: None,
    have_dlfcn_h: None,
    have_errno_h: Some(1),
    have_fcntl_h: Some(1),
    have_gssapi_gssapi_h: None,
    have_inttypes_h: None,
    have_libkrb5: None,
    have_libnsl: None,
    have_libsocket: None,
    have_linger: Some(1),
    have_netdb_h: None,
    have_netinet_in_h: Some(1),
    have_netinet_tcp_h: None,
    have_poll_h: None,
    have_sockaddr_len: None,
    have_sockaddr_storage: None,
    have_stdint_h: Some(1),
    have_stdio_h: Some(1),
    have_stdlib_h: Some(1),
    have_strings_h: None,
    have_string_h: Some(1),
    have_sys_errno_h: None,
    have_sys_fcntl_h: None,
    have_sys_ioctl_h: None,
    have_sys_poll_h: None,
    have_sys_socket_h: None,
    have_sys_stat_h: None,
    have_sys_time_h: None,
    have_sys_types_h: Some(1),
    have_sys_uio_h: None,
    have_sys_unistd_h: None,
    have_sys_iovec_h: None,
    have_time_h: Some(1),
    have_unistd_h: Some(1),
    lt_objdir: ".libs/",
    package: "libsmb2",
    package_bugreport: "ronniesahlberg@gmail.com",
    package_name: "libsmb2",
    package_string: "libsmb2 4.0.0",
    package_tarname: "libsmb2",
    package_url: "",
    package_version: "4.0.0",
    stdc_headers: Some(1),
    version: "4.0.0",
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct FreeRtosConfig {
    pub use_preemption: u32,
    pub use_tickless_idle: u32,
    pub tick_rate_hz: u32,
    pub max_priorities: u32,
    pub minimal_stack_size: u32,
    pub use_mutexes: u32,
    pub use_recursive_mutexes: u32,
    pub use_counting_semaphores: u32,
    pub queue_registry_size: u32,
    pub enable_backward_compatibility: u32,
    pub num_thread_local_storage_pointers: u32,
    pub stack_depth_type: &'static str,
    pub message_buffer_length_type: &'static str,
    pub support_static_allocation: u32,
    pub support_dynamic_allocation: u32,
    pub total_heap_size: u32,
    pub check_for_stack_overflow: u32,
    pub use_trace_facility: u32,
    pub use_co_routines: u32,
    pub use_timers: u32,
    pub timer_task_priority_delta: i32,
    pub timer_queue_length: u32,
    pub timer_task_stack_depth: u32,
    pub num_cores: Option<u32>,
    pub tick_core: Option<u32>,
    pub run_multiple_priorities: Option<u32>,
    pub use_core_affinity: Option<u32>,
    pub support_pico_sync_interop: u32,
    pub support_pico_time_interop: u32,
    pub assert_maps_to_assert: bool,
    pub include_v_task_priority_set: u32,
    pub include_ux_task_priority_get: u32,
    pub include_v_task_delete: u32,
    pub include_v_task_suspend: u32,
    pub include_v_task_delay_until: u32,
    pub include_v_task_delay: u32,
    pub include_x_task_get_scheduler_state: u32,
    pub include_x_task_get_current_task_handle: u32,
    pub include_ux_task_get_stack_high_water_mark: u32,
    pub include_x_task_get_idle_task_handle: u32,
    pub include_e_task_get_state: u32,
    pub include_x_timer_pend_function_call: u32,
    pub include_x_task_abort_delay: u32,
    pub include_x_task_get_handle: u32,
    pub include_x_task_resume_from_isr: u32,
    pub include_x_queue_get_mutex_holder: u32,
}

pub const PICOW_FREERTOS_CONFIG: FreeRtosConfig = FreeRtosConfig {
    use_preemption: 1,
    use_tickless_idle: 0,
    tick_rate_hz: 1000,
    max_priorities: 32,
    minimal_stack_size: 2048,
    use_mutexes: 1,
    use_recursive_mutexes: 1,
    use_counting_semaphores: 1,
    queue_registry_size: 8,
    enable_backward_compatibility: 1,
    num_thread_local_storage_pointers: 5,
    stack_depth_type: "uint32_t",
    message_buffer_length_type: "size_t",
    support_static_allocation: 0,
    support_dynamic_allocation: 1,
    total_heap_size: 128 * 1024,
    check_for_stack_overflow: 0,
    use_trace_facility: 1,
    use_co_routines: 0,
    use_timers: 1,
    timer_task_priority_delta: -1,
    timer_queue_length: 10,
    timer_task_stack_depth: 1024,
    num_cores: Some(2),
    tick_core: Some(0),
    run_multiple_priorities: Some(1),
    use_core_affinity: Some(1),
    support_pico_sync_interop: 1,
    support_pico_time_interop: 1,
    assert_maps_to_assert: true,
    include_v_task_priority_set: 1,
    include_ux_task_priority_get: 1,
    include_v_task_delete: 1,
    include_v_task_suspend: 1,
    include_v_task_delay_until: 1,
    include_v_task_delay: 1,
    include_x_task_get_scheduler_state: 1,
    include_x_task_get_current_task_handle: 1,
    include_ux_task_get_stack_high_water_mark: 1,
    include_x_task_get_idle_task_handle: 1,
    include_e_task_get_state: 1,
    include_x_timer_pend_function_call: 1,
    include_x_task_abort_delay: 1,
    include_x_task_get_handle: 1,
    include_x_task_resume_from_isr: 1,
    include_x_queue_get_mutex_holder: 1,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LwipOpts {
    pub so_rcvbuf: u32,
    pub timeval_private: u32,
    pub tcpip_thread_stacksize: Option<u32>,
    pub default_thread_stacksize: Option<u32>,
    pub default_raw_recvmbox_size: Option<u32>,
    pub tcpip_mbox_size: Option<u32>,
    pub default_udp_recvmbox_size_alias: Option<&'static str>,
    pub default_tcp_recvmbox_size_alias: Option<&'static str>,
    pub default_acceptmbox_size_alias: Option<&'static str>,
    pub tcpip_core_locking_input: Option<u32>,
}

pub const PICOW_LWIPOPTS: LwipOpts = LwipOpts {
    so_rcvbuf: 1,
    timeval_private: 0,
    tcpip_thread_stacksize: Some(1024),
    default_thread_stacksize: Some(1024),
    default_raw_recvmbox_size: Some(8),
    tcpip_mbox_size: Some(8),
    default_udp_recvmbox_size_alias: Some("TCPIP_MBOX_SIZE"),
    default_tcp_recvmbox_size_alias: Some("TCPIP_MBOX_SIZE"),
    default_acceptmbox_size_alias: Some("TCPIP_MBOX_SIZE"),
    tcpip_core_locking_input: Some(1),
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LwipCommonConfig {
    pub no_sys_default: u32,
    pub no_sys_preserves_caller_override: bool,
    pub lwip_socket_default: u32,
    pub lwip_socket_preserves_caller_override: bool,
    pub mem_libc_malloc_poll: u32,
    pub mem_libc_malloc_non_poll: u32,
    pub mem_alignment: u32,
    pub mem_size: u32,
    pub memp_num_tcp_seg: u32,
    pub memp_num_arp_queue: u32,
    pub pbuf_pool_size: u32,
    pub lwip_arp: u32,
    pub lwip_ethernet: u32,
    pub lwip_icmp: u32,
    pub lwip_raw: u32,
    pub tcp_wnd_expr: &'static str,
    pub tcp_mss: u32,
    pub tcp_snd_buf_expr: &'static str,
    pub tcp_snd_queuelen_expr: &'static str,
    pub lwip_netif_status_callback: u32,
    pub lwip_netif_link_callback: u32,
    pub lwip_netif_hostname: u32,
    pub lwip_netconn: u32,
    pub mem_stats: u32,
    pub sys_stats: u32,
    pub memp_stats: u32,
    pub link_stats: u32,
    pub lwip_chksum_algorithm: u32,
    pub lwip_dhcp: u32,
    pub lwip_ipv4: u32,
    pub lwip_tcp: u32,
    pub lwip_udp: u32,
    pub lwip_dns: u32,
    pub lwip_tcp_keepalive: u32,
    pub lwip_netif_tx_single_pbuf: u32,
    pub dhcp_does_arp_check: u32,
    pub lwip_dhcp_does_acd_check: u32,
    pub lwip_debug: Option<u32>,
    pub lwip_stats: Option<u32>,
    pub lwip_stats_display: Option<u32>,
    pub debug_categories: &'static [&'static str],
    pub debug_category_value: &'static str,
}
pub const PICOW_LWIP_COMMON: LwipCommonConfig = LwipCommonConfig {
    no_sys_default: 1,
    no_sys_preserves_caller_override: true,
    lwip_socket_default: 1,
    lwip_socket_preserves_caller_override: true,
    mem_libc_malloc_poll: 1,
    mem_libc_malloc_non_poll: 0,
    mem_alignment: 4,
    mem_size: 4000,
    memp_num_tcp_seg: 32,
    memp_num_arp_queue: 10,
    pbuf_pool_size: 24,
    lwip_arp: 1,
    lwip_ethernet: 1,
    lwip_icmp: 1,
    lwip_raw: 1,
    tcp_wnd_expr: "8 * TCP_MSS",
    tcp_mss: 1460,
    tcp_snd_buf_expr: "8 * TCP_MSS",
    tcp_snd_queuelen_expr: "(4 * (TCP_SND_BUF) + (TCP_MSS - 1)) / (TCP_MSS)",
    lwip_netif_status_callback: 1,
    lwip_netif_link_callback: 1,
    lwip_netif_hostname: 1,
    lwip_netconn: 0,
    mem_stats: 0,
    sys_stats: 0,
    memp_stats: 0,
    link_stats: 0,
    lwip_chksum_algorithm: 3,
    lwip_dhcp: 1,
    lwip_ipv4: 1,
    lwip_tcp: 1,
    lwip_udp: 1,
    lwip_dns: 1,
    lwip_tcp_keepalive: 1,
    lwip_netif_tx_single_pbuf: 1,
    dhcp_does_arp_check: 0,
    lwip_dhcp_does_acd_check: 0,
    lwip_debug: Some(1),
    lwip_stats: Some(1),
    lwip_stats_display: Some(1),
    debug_categories: &[
        "ETHARP_DEBUG",
        "NETIF_DEBUG",
        "PBUF_DEBUG",
        "API_LIB_DEBUG",
        "API_MSG_DEBUG",
        "SOCKETS_DEBUG",
        "ICMP_DEBUG",
        "INET_DEBUG",
        "IP_DEBUG",
        "IP_REASS_DEBUG",
        "RAW_DEBUG",
        "MEM_DEBUG",
        "MEMP_DEBUG",
        "SYS_DEBUG",
        "TCP_DEBUG",
        "TCP_INPUT_DEBUG",
        "TCP_OUTPUT_DEBUG",
        "TCP_RTO_DEBUG",
        "TCP_CWND_DEBUG",
        "TCP_WND_DEBUG",
        "TCP_FR_DEBUG",
        "TCP_QLEN_DEBUG",
        "TCP_RST_DEBUG",
        "UDP_DEBUG",
        "TCPIP_DEBUG",
        "PPP_DEBUG",
        "SLIP_DEBUG",
        "DHCP_DEBUG",
    ],
    debug_category_value: "LWIP_DBG_OFF",
};
